BUGSCRAPER_VERSION = "0.10"
DISTRIBUTION_PLATFORM = "default" -- default | itchio | steam
GAME_TYPE = "normal" -- normal | demo

INPUT_FILE_FORMAT_VERSION = 4
METAPROGRESSION_FILE_FORMAT_VERSION = 3
OPTIONS_FILE_FORMAT_VERSION = 2
DEMO_BUILD = false
BETA_BUILD = true

DEBUG_MODE = true
PROFILE_INIT = false